//
// This file was generated by the JPA Modeler
//
package ci.kossovo.ecole.entity;

import org.springframework.data.mongodb.core.mapping.Document;

@Document
public class Filiere extends AbstractEntity {
	private static final long serialVersionUID = 1L;

	private String libelle;

	private String description;

	public Filiere() {

	}

	
	
	public Filiere(String libelle, String description) {
		super();
		this.libelle = libelle;
		this.description = description;
	}

	@Override
	public String toString() {
		return String.format("Filiere[%s]",libelle);
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
