//
// This file was generated by the JPA Modeler
//
package ci.kossovo.ecole.entity;

import org.springframework.data.mongodb.core.mapping.Document;

@Document
public class Matiere extends AbstractEntity {
	private static final long serialVersionUID = 1L;

	private String libelle;

	private String description;

	public Matiere() {

	}

	public Matiere(String libelle, String description) {
		super();
		this.libelle = libelle;
		this.description = description;
	}

	@Override
	public String toString() {
		return String.format("Matiere[%s,%s,%s]", libelle);
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
