//
// This file was generated by the JPA Modeler
//
package ci.kossovo.ecole.entity;

public abstract class Personne extends AbstractEntity {
	private static final long serialVersionUID = 1L;

	private String titre;

	
	private Adresse adresse;

	private String nom;

	private String prenom;
	private String numCni;

	private String nomComplet;

	
	private String type;

	public Personne() {

	}

	public Personne(String titre, Adresse adresse, String nom, String prenom) {
		super();
		this.titre = titre;
		this.adresse = adresse;
		this.nom = nom;
		this.prenom = prenom;
	}

	public Personne(String titre, String nom, String prenom) {
		super();
		this.titre = titre;
		this.nom = nom;
		this.prenom = prenom;
	}
	
	
	

	public Personne(String titre, String nom, String prenom, String numCni) {
		super();
		this.titre = titre;
		this.nom = nom;
		this.prenom = prenom;
		this.numCni = numCni;
	}

	@Override
	public String toString() {
		return String.format("Personne[%s,%s,%s,%s]", id, titre, nom,prenom);
	}

	public String getNomComplet() {
		return nomComplet;
	}

	
	public void setNomComplet() {
		this.nomComplet = nom + " " + prenom;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public Adresse getAdresse() {
		return this.adresse;
	}

	public void setAdresse(Adresse adresse) {
		this.adresse = adresse;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getNumCni() {
		return numCni;
	}

	public void setNumCni(String numCni) {
		this.numCni = numCni;
	}
	
	

}
